CREATE TABLE highscores (
    device_id TEXT PRIMARY KEY,
    display_name TEXT,
    score NUMERIC NOT NULL DEFAULT -1
);

INSERT INTO highscores(device_id, display_name, score)
VALUES
('test_device_05', 'AstonishingStove', 3),
('test_device_06', 'AttractiveStranger', 3),
('test_device_25', 'BerserkTable', 41),
('test_device_12', 'AwareStructure', 17),
('test_device_23', 'BeneficialSwing', 42),
('test_device_20', 'BeautifulSurprise', 2),
('test_device_21', 'BefittingSweater', 25),
('test_device_00', 'AromaticStomach', 6),
('test_device_39', 'BlushingTexture', 2),
('test_device_40', 'BoilingTheory', 23),
('test_device_49', 'BrawnyThunder', 05),
('test_device_16', 'BadSuit', 34),
('test_device_17', 'BarbarousSummer', 2),
('test_device_19', 'BawdySupport', 03),
('test_device_03', 'AspiringStore', 2),
('test_device_04', 'AssortedStory', 2),
('test_device_24', 'BentSystem', 6),
('test_device_13', 'AwesomeSubstance', 18),
('test_device_14', 'AwfulSugar', 3),
('test_device_29', 'BigTaste', 6),
('test_device_50', 'BreakableTicket', 01),
('test_device_51', 'BreezyTiger', 06),
('test_device_44', 'BouncyThread', 6),
('test_device_26', 'BestTail', 6),
('test_device_33', 'BizarreTeeth', 11),
('test_device_34', 'BlackTemper', 5),
('test_device_30', 'BillowyTax', 1),
('test_device_32', 'BitterTeam', 2),
('test_device_47', 'BrashThrone', 14),
('test_device_48', 'BraveThumb', 04),
('test_device_10', 'AverageStretch', 1),
('test_device_36', 'BloodyTent', 5),
('test_device_11', 'AwakeString', 02),
('test_device_41', 'BoorishThing', 24),
('test_device_42', 'BoredThings', 5),
('test_device_22', 'BelligerentSwim', 3),
('test_device_01', 'ArrogantStone', 7),
('test_device_02', 'AshamedStop', 7),
('test_device_09', 'AvailableStreet', 15),
('test_device_18', 'BashfulSun', 2),
('test_device_37', 'BlueTerritory', 22),
('test_device_45', 'BoundlessThrill', 12),
('test_device_46', 'BrainyThroat', 8),
('test_device_52', 'BriefTime', 07),
('test_device_15', 'AxiomaticSuggestion', 21),
('test_device_07', 'AuspiciousStraw', 2),
('test_device_08', 'AutomaticStream', 1),
('test_device_43', 'BoringThought', 28),
('test_device_27', 'BetterTalk', 5),
('test_device_28', 'BewilderedTank', 1)